/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import Controlador.ControladorPaciente;
import Modelo.AntecedentesMedicos;
import Modelo.Paciente;
/**
 *
 * @author ACER
 */
public class FrmActualizarPaciente extends javax.swing.JFrame {
    private ControladorPaciente controladorPaciente;
    private Paciente pacienteEncontrado;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmActualizarPaciente.class.getName());

    /**
     * Creates new form FrmActualizarPaciente
     */
    public FrmActualizarPaciente(ControladorPaciente controladorPaciente) {
        initComponents();
        this.controladorPaciente = controladorPaciente;
        setLocationRelativeTo(null);
        lblMensaje.setText("");
        habilitarFormulario(false);
    }
    private void habilitarFormulario(boolean estado) {
        txtDireccion.setEnabled(estado);
        txtTelefono.setEnabled(estado);
        rbAppSi.setEnabled(estado);
        rbAppNo.setEnabled(estado);
        rbCirugiaSi.setEnabled(estado);
        rbCirugiasNo.setEnabled(estado);
        rbIntoxiSi.setEnabled(estado);
        rbIntoxiNo.setEnabled(estado);
        rbTrabajoSi.setEnabled(estado);
        rbTrabajoNo.setEnabled(estado);
        rbDeporteSi.setEnabled(estado);
        rbDeporteNo.setEnabled(estado);
        txtPeso.setEnabled(estado);
        txtTalla.setEnabled(estado);
        txtPA.setEnabled(estado);
        btnGuardar.setEnabled(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarNumDoc = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        jpNoEditable = new javax.swing.JPanel();
        lblHC = new javax.swing.JLabel();
        txtHC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipoDoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jpEditable = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbIntoxiSi = new javax.swing.JRadioButton();
        rbIntoxiNo = new javax.swing.JRadioButton();
        lblTrabajo = new javax.swing.JLabel();
        rbTrabajoSi = new javax.swing.JRadioButton();
        rbTrabajoNo = new javax.swing.JRadioButton();
        lblDeporte = new javax.swing.JLabel();
        rbDeporteSi = new javax.swing.JRadioButton();
        rbDeporteNo = new javax.swing.JRadioButton();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblTalla = new javax.swing.JLabel();
        txtTalla = new javax.swing.JTextField();
        lblIMC = new javax.swing.JLabel();
        txtIMC = new javax.swing.JTextField();
        lblPA = new javax.swing.JLabel();
        lblApp = new javax.swing.JLabel();
        txtPA = new javax.swing.JTextField();
        rbAppSi = new javax.swing.JRadioButton();
        btnCalcularIMC = new javax.swing.JButton();
        rbAppNo = new javax.swing.JRadioButton();
        lblCirugia = new javax.swing.JLabel();
        rbCirugiaSi = new javax.swing.JRadioButton();
        rbCirugiasNo = new javax.swing.JRadioButton();
        lblIntoxi = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        jLabel1.setText("Ingrese el N° de Documento del Paciente:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout jpBusquedaLayout = new javax.swing.GroupLayout(jpBusqueda);
        jpBusqueda.setLayout(jpBusquedaLayout);
        jpBusquedaLayout.setHorizontalGroup(
            jpBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBusquedaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBusquedaLayout.setVerticalGroup(
            jpBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpNoEditable.setBorder(javax.swing.BorderFactory.createTitledBorder("No Editable"));

        lblHC.setText("HC:");

        txtHC.setEnabled(false);

        jLabel2.setText("Tipo de Documento:");

        txtTipoDoc.setEnabled(false);

        jLabel3.setText("N° de Documento:");

        txtNumDoc.setEnabled(false);

        javax.swing.GroupLayout jpNoEditableLayout = new javax.swing.GroupLayout(jpNoEditable);
        jpNoEditable.setLayout(jpNoEditableLayout);
        jpNoEditableLayout.setHorizontalGroup(
            jpNoEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNoEditableLayout.createSequentialGroup()
                .addGroup(jpNoEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNoEditableLayout.createSequentialGroup()
                        .addComponent(lblHC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpNoEditableLayout.setVerticalGroup(
            jpNoEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNoEditableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNoEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHC)
                    .addComponent(txtHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jpEditable.setBorder(javax.swing.BorderFactory.createTitledBorder("Editable"));

        jLabel5.setText("Dirección:");

        jLabel6.setText("Teléfono:");

        rbIntoxiSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbIntoxiSi.setText("Si");

        rbIntoxiNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbIntoxiNo.setText("No");

        lblTrabajo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTrabajo.setText("Trabajo:");

        rbTrabajoSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbTrabajoSi.setText("Si");

        rbTrabajoNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbTrabajoNo.setText("No");

        lblDeporte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDeporte.setText("Deporte:");

        rbDeporteSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbDeporteSi.setText("Si");

        rbDeporteNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbDeporteNo.setText("No");

        lblPeso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPeso.setText("Peso:");

        txtPeso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblTalla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTalla.setText("Talla:");

        txtTalla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblIMC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIMC.setText("IMC:");

        txtIMC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIMC.setEnabled(false);

        lblPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPA.setText("PA:");

        lblApp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblApp.setText("APP:");

        txtPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        rbAppSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbAppSi.setText("Si");

        btnCalcularIMC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCalcularIMC.setText("Calcular IMC");
        btnCalcularIMC.addActionListener(this::btnCalcularIMCActionPerformed);

        rbAppNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbAppNo.setText("No");

        lblCirugia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCirugia.setText("Cirugías:");

        rbCirugiaSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbCirugiaSi.setText("Si");

        rbCirugiasNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbCirugiasNo.setText("No");

        lblIntoxi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIntoxi.setText("Intoxicación:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout jpEditableLayout = new javax.swing.GroupLayout(jpEditable);
        jpEditable.setLayout(jpEditableLayout);
        jpEditableLayout.setHorizontalGroup(
            jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditableLayout.createSequentialGroup()
                .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEditableLayout.createSequentialGroup()
                        .addComponent(lblCirugia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCirugiaSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCirugiasNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEditableLayout.createSequentialGroup()
                        .addComponent(lblIntoxi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbIntoxiSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbIntoxiNo))
                    .addGroup(jpEditableLayout.createSequentialGroup()
                        .addComponent(lblTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTrabajoSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTrabajoNo)
                        .addGap(18, 18, 18)
                        .addComponent(lblDeporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDeporteSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDeporteNo))
                    .addGroup(jpEditableLayout.createSequentialGroup()
                        .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEditableLayout.createSequentialGroup()
                                .addComponent(lblPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpEditableLayout.createSequentialGroup()
                                .addComponent(lblPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEditableLayout.createSequentialGroup()
                                .addComponent(lblTalla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblIMC))
                            .addGroup(jpEditableLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnCalcularIMC)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEditableLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEditableLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 122, Short.MAX_VALUE))
            .addGroup(jpEditableLayout.createSequentialGroup()
                .addComponent(lblApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAppSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAppNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(50, 50, 50)
                .addComponent(btnCancelar)
                .addGap(241, 241, 241))
        );
        jpEditableLayout.setVerticalGroup(
            jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApp)
                    .addComponent(rbAppSi)
                    .addComponent(rbAppNo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCirugia)
                    .addComponent(rbCirugiaSi)
                    .addComponent(rbCirugiasNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntoxi)
                    .addComponent(rbIntoxiSi)
                    .addComponent(rbIntoxiNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrabajo)
                    .addComponent(rbTrabajoSi)
                    .addComponent(rbTrabajoNo)
                    .addComponent(lblDeporte)
                    .addComponent(rbDeporteSi)
                    .addComponent(rbDeporteNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTalla)
                    .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIMC)
                    .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPA)
                    .addComponent(btnCalcularIMC))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpNoEditable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpEditable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpNoEditable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEditable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIMCActionPerformed
        try {
            double peso = Double.parseDouble(txtPeso.getText().trim());
            double talla = Double.parseDouble(txtTalla.getText().trim());

            if (peso <= 0 || talla <= 0) {
                lblMensaje.setForeground(java.awt.Color.RED);
                lblMensaje.setText("Peso y talla deben ser mayores a 0.");
                return;
            }

            double tallaMetros = talla / 100.0;
            double imc = peso / (tallaMetros * tallaMetros);

            txtIMC.setText(String.format("%.2f", imc));
            lblMensaje.setForeground(new java.awt.Color(0, 128, 0));
            lblMensaje.setText("IMC calculado correctamente.");

        } catch (NumberFormatException e) {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText("Ingrese valores numéricos válidos en Peso y Talla.");
        }
    }//GEN-LAST:event_btnCalcularIMCActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    // Busca al paciente y carga sus datos en el formulario
    String dni = txtBuscarNumDoc.getText().trim();

        if (dni.isEmpty()) {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText("Ingrese un DNI para buscar.");
            return;
        }

        pacienteEncontrado = controladorPaciente.buscarPorDNI(dni);

        if (pacienteEncontrado == null) {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText("No se encontró ningún paciente con ese criterio de búsqueda.");
            habilitarFormulario(false);
            limpiarFormulario();
            return;
        }

        cargarDatosPaciente();
        habilitarFormulario(true);
        lblMensaje.setForeground(new java.awt.Color(0, 128, 0));
        lblMensaje.setText("Paciente encontrado. Puede actualizar dirección, teléfono y antecedentes.");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
        // REQ-29 y REQ-30: confirmación y guardado

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    if (pacienteEncontrado == null) {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText("Primero busque un paciente válido.");
            return;
        }

        // REQ-29: confirmación antes de guardar
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea actualizar los datos del paciente?",
            "Confirmar actualización",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // REQ-27: actualizar dirección y teléfono
            pacienteEncontrado.setDireccion(txtDireccion.getText().trim());
            pacienteEncontrado.setTelefono(txtTelefono.getText().trim());

            // REQ-27: actualizar antecedentes médicos
            double peso = Double.parseDouble(txtPeso.getText().trim());
            double talla = Double.parseDouble(txtTalla.getText().trim());
            String pa = txtPA.getText().trim();

            AntecedentesMedicos ant = pacienteEncontrado.getAntecedentes();
            if (ant == null) {
                ant = new AntecedentesMedicos();
            }

            ant.setApp(rbAppSi.isSelected());
            ant.setCirugias(rbCirugiaSi.isSelected());
            ant.setIntoxicacion(rbIntoxiSi.isSelected());
            ant.setTrabajo(rbTrabajoSi.isSelected());
            ant.setDeporte(rbDeporteSi.isSelected());
            ant.setPeso(peso);
            ant.setTalla(talla);
            ant.setPa(pa);

            pacienteEncontrado.setAntecedentes(ant);

            // Refrescar el IMC mostrado
            txtIMC.setText(String.format("%.2f", ant.getImc()));

            // REQ-30: mensaje de éxito
            lblMensaje.setForeground(new java.awt.Color(0, 128, 0));
            lblMensaje.setText("Datos del paciente actualizados correctamente.");

        } catch (NumberFormatException e) {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText("Ingrese valores numéricos válidos en Peso y Talla.");
        } catch (IllegalArgumentException e) {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText(e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    private void cargarDatosPaciente() {
        // REQ-28: campos no editables, solo informativos
        txtHC.setText(String.valueOf(pacienteEncontrado.getNumHC()));
        txtTipoDoc.setText(pacienteEncontrado.getTipodoc());
        txtNumDoc.setText(pacienteEncontrado.getNumdoc());
        lblNombre.setText("Paciente: " + pacienteEncontrado.getNombreCompleto());

        // REQ-27: campos editables
        txtDireccion.setText(pacienteEncontrado.getDireccion());
        txtTelefono.setText(pacienteEncontrado.getTelefono());

        AntecedentesMedicos ant = pacienteEncontrado.getAntecedentes();
        if (ant != null) {
            rbAppSi.setSelected(ant.isApp());
            rbAppNo.setSelected(!ant.isApp());

            rbCirugiaSi.setSelected(ant.isCirugias());
            rbCirugiasNo.setSelected(!ant.isCirugias());

            rbIntoxiSi.setSelected(ant.isIntoxicacion());
            rbIntoxiNo.setSelected(!ant.isIntoxicacion());

            rbTrabajoSi.setSelected(ant.isTrabajo());
            rbTrabajoNo.setSelected(!ant.isTrabajo());

            rbDeporteSi.setSelected(ant.isDeporte());
            rbDeporteNo.setSelected(!ant.isDeporte());

            txtPeso.setText(String.valueOf(ant.getPeso()));
            txtTalla.setText(String.valueOf(ant.getTalla()));
            txtIMC.setText(String.format("%.2f", ant.getImc()));
            txtPA.setText(ant.getPa());
        }
        
    }
    // REQ-28: si el usuario intenta editar HC o DNI, se le informa
    private void txtHCFocusGained(java.awt.event.FocusEvent evt) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("Este campo no puede ser modificado.");
    }
    private void txtNumDocFocusGained(java.awt.event.FocusEvent evt) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("Este campo no puede ser modificado.");
    }

    
    private void limpiarFormulario() {
        txtHC.setText("");
        txtBuscarNumDoc.setText("");
        lblNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtPeso.setText("");
        txtTalla.setText("");
        txtIMC.setText("");
        txtPA.setText("");
    }
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalcularIMC;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jpBusqueda;
    private javax.swing.JPanel jpEditable;
    private javax.swing.JPanel jpNoEditable;
    private javax.swing.JLabel lblApp;
    private javax.swing.JLabel lblCirugia;
    private javax.swing.JLabel lblDeporte;
    private javax.swing.JLabel lblHC;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblIntoxi;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPA;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JLabel lblTrabajo;
    private javax.swing.JRadioButton rbAppNo;
    private javax.swing.JRadioButton rbAppSi;
    private javax.swing.JRadioButton rbCirugiaSi;
    private javax.swing.JRadioButton rbCirugiasNo;
    private javax.swing.JRadioButton rbDeporteNo;
    private javax.swing.JRadioButton rbDeporteSi;
    private javax.swing.JRadioButton rbIntoxiNo;
    private javax.swing.JRadioButton rbIntoxiSi;
    private javax.swing.JRadioButton rbTrabajoNo;
    private javax.swing.JRadioButton rbTrabajoSi;
    private javax.swing.JTextField txtBuscarNumDoc;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtHC;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoDoc;
    // End of variables declaration//GEN-END:variables
}
