/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import Controlador.ControladorPaciente;
import Modelo.Paciente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FrmBusquedaPaciente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBusquedaPaciente.class.getName());

    /**
     * Creates new form FrmBusquedaPaciente
     */
    private ControladorPaciente controladorPaciente;
    private ArrayList<Paciente> resultadosBusqueda;
    
    public FrmBusquedaPaciente(ControladorPaciente controladorPaciente) {
        initComponents();
        this.controladorPaciente = controladorPaciente;
        setLocationRelativeTo(null);
        lblMensaje.setText("");
        btnVer.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBuscarPaciente = new javax.swing.JPanel();
        lblCriterio = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jpResultados = new javax.swing.JPanel();
        jscResultados = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpBotones = new javax.swing.JPanel();
        btnVer = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBuscarPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Paciente"));

        lblCriterio.setText("Buscar por DNI o Nombre/Apellido:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout jpBuscarPacienteLayout = new javax.swing.GroupLayout(jpBuscarPaciente);
        jpBuscarPaciente.setLayout(jpBuscarPacienteLayout);
        jpBuscarPacienteLayout.setHorizontalGroup(
            jpBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscarPacienteLayout.createSequentialGroup()
                .addComponent(lblCriterio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addContainerGap())
        );
        jpBuscarPacienteLayout.setVerticalGroup(
            jpBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCriterio)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N° HC", "Nombres", "Apellidos", "TipoDoc", "NumDoc", "Edad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jscResultados.setViewportView(jTable1);

        javax.swing.GroupLayout jpResultadosLayout = new javax.swing.GroupLayout(jpResultados);
        jpResultados.setLayout(jpResultadosLayout);
        jpResultadosLayout.setHorizontalGroup(
            jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );
        jpResultadosLayout.setVerticalGroup(
            jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jscResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnVer.setText("Ver Historia Clínica");
        btnVer.addActionListener(this::btnVerActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBotonesLayout.createSequentialGroup()
                        .addComponent(btnVer)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotonesLayout.createSequentialGroup()
                        .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVer)
                    .addComponent(btnCerrar))
                .addGap(18, 18, 18)
                .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBuscarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    String criterio = txtBuscar.getText().trim();

    if (criterio.isEmpty()) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("Ingrese un DNI o nombre para buscar.");
        return;
    }

    resultadosBusqueda = controladorPaciente.buscarPacientes(criterio);

    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);

    if (resultadosBusqueda.isEmpty()) {
        // REQ-23
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("No se encontró ningún paciente con ese criterio de búsqueda.");
        btnVer.setEnabled(false);
    } else {
        // REQ-24
        for (Paciente p : resultadosBusqueda) {
            Object[] fila = {
                p.getNumHC(),
                p.getNombre(),
                p.getPaterno() + " " + p.getMaterno(),
                p.getTipodoc(),
                p.getNumdoc(),
                p.getEdad()
            };
            modelo.addRow(fila);
        }
        lblMensaje.setForeground(new java.awt.Color(0, 128, 0));
        lblMensaje.setText("Se encontraron " + resultadosBusqueda.size() + " paciente(s).");
        btnVer.setEnabled(true);
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
    int filaSeleccionada = jTable1.getSelectedRow();

    if (filaSeleccionada == -1) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("Seleccione un paciente de la tabla.");
        return;
    }

    int numHC = (int) jTable1.getValueAt(filaSeleccionada, 0);

    Paciente pacienteSeleccionado = null;
    for (Paciente p : resultadosBusqueda) {
        if (p.getNumHC() == numHC) {
            pacienteSeleccionado = p;
            break;
        }
    }

    if (pacienteSeleccionado != null) {
        FrmHistoriaClinica frm = new FrmHistoriaClinica(pacienteSeleccionado);
        frm.setVisible(true);
    }
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVer;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpBuscarPaciente;
    private javax.swing.JPanel jpResultados;
    private javax.swing.JScrollPane jscResultados;
    private javax.swing.JLabel lblCriterio;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
