/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Controlador.ControladorPaciente;

/**
 *
 * @author ACER
 */
public class FrmEliminarPaciente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEliminarPaciente.class.getName());
    private final ControladorPaciente controladorPaciente;

    /**
     * Creates new form FrmEliminarPaciente
     */
    public FrmEliminarPaciente(ControladorPaciente cp) {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Ventana/Logo.png")).getImage());
        this.controladorPaciente = cp;
        btnEliminar.setEnabled(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPEliminarPaciente = new javax.swing.JPanel();
        lbldni = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPEliminarPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Paciente"));

        lbldni.setText("DNI:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        txtDatos.setColumns(20);
        txtDatos.setRows(5);
        jScrollPane1.setViewportView(txtDatos);

        javax.swing.GroupLayout JPEliminarPacienteLayout = new javax.swing.GroupLayout(JPEliminarPaciente);
        JPEliminarPaciente.setLayout(JPEliminarPacienteLayout);
        JPEliminarPacienteLayout.setHorizontalGroup(
            JPEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEliminarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addGroup(JPEliminarPacienteLayout.createSequentialGroup()
                        .addComponent(lbldni, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        JPEliminarPacienteLayout.setVerticalGroup(
            JPEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEliminarPacienteLayout.createSequentialGroup()
                .addGroup(JPEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPEliminarPacienteLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(JPEliminarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldni)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(lblResultado)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar))
                    .addGroup(JPEliminarPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPEliminarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    String dni = txtDNI.getText().trim();
if (dni.isEmpty()) {
    lblResultado.setText("Ingrese un DNI.");
    lblResultado.setForeground(java.awt.Color.RED);
    return;
}

Modelo.Paciente p = controladorPaciente.buscarPorDNI(dni);
if (p != null) {
    txtDatos.setText(
        "N° HC:    " + p.getNumHC() + "\n" +
        "Nombre:   " + p.getNombreCompleto() + "\n" +
        "DNI:      " + p.getNumdoc() + "\n" +
        "Edad:     " + p.getEdad() + " años\n" +
        "Teléfono: " + p.getTelefono()
    );
    lblResultado.setText("Paciente encontrado. Confirme la eliminación.");
    lblResultado.setForeground(new java.awt.Color(0, 128, 0));
    btnEliminar.setEnabled(true);
} else {
    txtDatos.setText("");
    lblResultado.setText("No se encontró un paciente con ese DNI.");
    lblResultado.setForeground(java.awt.Color.RED);
    btnEliminar.setEnabled(false);
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    String dni = txtDNI.getText().trim();
int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
    this,
    "¿Está seguro de eliminar al paciente con DNI " + dni + "?",
    "Confirmar eliminación",
    javax.swing.JOptionPane.YES_NO_OPTION
);

if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
    boolean eliminado = controladorPaciente.eliminarPaciente(dni);
    if (eliminado) {
        lblResultado.setText("Paciente eliminado correctamente.");
        lblResultado.setForeground(new java.awt.Color(0, 128, 0));
        txtDatos.setText("");
        txtDNI.setText("");
        btnEliminar.setEnabled(false);
    } else {
        lblResultado.setText("Error al eliminar.");
        lblResultado.setForeground(java.awt.Color.RED);
    }
}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPEliminarPaciente;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lbldni;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextArea txtDatos;
    // End of variables declaration//GEN-END:variables
}
