/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import Controlador.ControladorPaciente;
import Modelo.Paciente;
import Modelo.Consulta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class FrmHistoriaClinica extends javax.swing.JFrame {
    private Paciente paciente;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmHistoriaClinica.class.getName());
    private final ControladorPaciente controladorPaciente;

    /**
     * Creates new form FrmHistoriaClinica
     */
    public FrmHistoriaClinica(ControladorPaciente cp, Paciente paciente) {
    initComponents();
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Ventana/Logo.png")).getImage());
    this.controladorPaciente = cp;
    this.paciente = paciente;
    setLocationRelativeTo(null);
    cargarDatosPaciente();
}
    private void mostrarDetalleConsulta(Consulta c) {
    javax.swing.JTextArea area = new javax.swing.JTextArea();
    area.setEditable(false);
    area.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 13));
    area.setLineWrap(true);
    area.setWrapStyleWord(true);
    area.setText(
        "Fecha:        " + c.getFecha() + "\n\n" +
        "Motivo:\n" + c.getMotivoconsulta() + "\n\n" +
        "IMC:          " + String.format("%.2f", c.getImc()) + "\n" +
        "PA:           " + c.getPa() + "\n" +
        "O3:           " + c.getO3() + "\n" +
        "PRP:          " + c.getPrp() + "\n" +
        "Terapia:      " + c.getTerapia() + "\n\n" +
        "Indicaciones:\n" + c.getIndicaciones() + "\n\n" +
        "Diagnóstico:\n" + c.getDiagnostico()
    );

    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(area);
    scroll.setPreferredSize(new java.awt.Dimension(500, 350));

    javax.swing.JOptionPane.showMessageDialog(
        this,
        scroll,
        "Detalle de Consulta - " + c.getFecha(),
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );
}
    private void cargarDatosPaciente() {
    // Datos generales
    lblHC.setText("" + paciente.getNumHC());
    lblNombreCompleto.setText("" + paciente.getNombreCompleto());
    lblTipoDoc.setText("" + paciente.getTipodoc());
    lblNumDoc.setText("" + paciente.getNumdoc());
    lblSexo.setText("" + paciente.getSexo());
    lblEdad.setText("" + paciente.getEdad());
    lblFechaNaci.setText("" + paciente.getFechanaci());
    lblDirecci.setText("" + paciente.getDireccion());
    lblTele.setText("" + paciente.getTelefono());

    // Antecedentes con historial de fechas
    if (paciente.getAntecedentes() != null) {
    StringBuilder sb = new StringBuilder();
    ArrayList<String> snapshots = paciente.getAntecedentes().getHistorialAntecedentes();

    if (snapshots == null || snapshots.isEmpty()) {
        sb.append("Sin antecedentes registrados.");
    } else {
        for (int i = 0; i < snapshots.size(); i++) {
            if (i == 0) {
                sb.append("=== REGISTRO INICIAL ===\n");
            } else {
                sb.append("\n=== ACTUALIZACIÓN ").append(i).append(" ===\n");
            }
            sb.append(snapshots.get(i)).append("\n");
        }
    }
    txtareaAntecedentes.setText(sb.toString());
    } else {
    txtareaAntecedentes.setText("Sin antecedentes registrados.");
    }
    txtareaAntecedentes.setEnabled(false);

    // Historial de consultas
    DefaultTableModel modelo = (DefaultTableModel) tblConsultas.getModel();
    modelo.setRowCount(0);
    for (Consulta c : paciente.getConsultas()) {
        modelo.addRow(new Object[]{
            c.getFecha(),
            c.getMotivoconsulta(),
            String.format("%.2f", c.getImc()),
            c.getPa(),
            c.getO3(),
            c.getPrp(),
            c.getTerapia(),
            c.getDiagnostico()
        });
    }
    tblConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int fila = tblConsultas.getSelectedRow();
        if (fila >= 0) {
            Consulta c = paciente.getConsultas().get(fila);
            mostrarDetalleConsulta(c);
        }
    }
});
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblHC = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        lblTipoDoc = new javax.swing.JLabel();
        lblNumDoc = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblFechaNaci = new javax.swing.JLabel();
        lblDirecci = new javax.swing.JLabel();
        lblTele = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jpAntecedentes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaAntecedentes = new javax.swing.JTextArea();
        jpConsultas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        jLabel1.setText("N° HC:");

        jLabel2.setText("Nombre Completo:");

        jLabel3.setText("Tipo de Documento:");

        jLabel4.setText("N° de Documento:");

        jLabel5.setText("Sexo:");

        jLabel6.setText("Edad:");

        jLabel7.setText("Fecha de Nacimiento:");

        jLabel8.setText("Dirección:");

        jLabel9.setText("Teléfono:");

        lblHC.setText("jLabel10");

        lblNombreCompleto.setText("jLabel11");

        lblTipoDoc.setText("jLabel12");

        lblNumDoc.setText("jLabel13");

        lblSexo.setText("jLabel14");

        lblEdad.setText("jLabel15");

        lblFechaNaci.setText("jLabel16");

        lblDirecci.setText("jLabel17");

        lblTele.setText("jLabel18");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTele, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDirecci, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(538, Short.MAX_VALUE))
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHC, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)
                        .addGap(34, 34, 34))))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(lblHC)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNombreCompleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTipoDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNumDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblFechaNaci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblDirecci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTele))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jpAntecedentes.setBorder(javax.swing.BorderFactory.createTitledBorder("Antecedentes"));

        txtareaAntecedentes.setColumns(20);
        txtareaAntecedentes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtareaAntecedentes.setForeground(new java.awt.Color(0, 0, 0));
        txtareaAntecedentes.setLineWrap(true);
        txtareaAntecedentes.setRows(5);
        txtareaAntecedentes.setWrapStyleWord(true);
        txtareaAntecedentes.setEnabled(false);
        jScrollPane1.setViewportView(txtareaAntecedentes);

        jpConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultas"));

        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Motivo", "IMC", "PA", "O3", "PRP", "Terapia", "Diagnostico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblConsultas);

        javax.swing.GroupLayout jpConsultasLayout = new javax.swing.GroupLayout(jpConsultas);
        jpConsultas.setLayout(jpConsultasLayout);
        jpConsultasLayout.setHorizontalGroup(
            jpConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1434, Short.MAX_VALUE)
        );
        jpConsultasLayout.setVerticalGroup(
            jpConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpAntecedentesLayout = new javax.swing.GroupLayout(jpAntecedentes);
        jpAntecedentes.setLayout(jpAntecedentesLayout);
        jpAntecedentesLayout.setHorizontalGroup(
            jpAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jpAntecedentesLayout.setVerticalGroup(
            jpAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAntecedentesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpAntecedentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAntecedentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpAntecedentes;
    private javax.swing.JPanel jpConsultas;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JLabel lblDirecci;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFechaNaci;
    private javax.swing.JLabel lblHC;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblNumDoc;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTele;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JTable tblConsultas;
    private javax.swing.JTextArea txtareaAntecedentes;
    // End of variables declaration//GEN-END:variables
}
