/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Controlador.ControladorPaciente;

/**
 *
 * @author ACER
 */
public class FrmListadoPacientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmListadoPacientes.class.getName());
    private final ControladorPaciente controladorPaciente;

    /**
     * Creates new form FrmListadoPacientes
     */
    public FrmListadoPacientes(ControladorPaciente cp) {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Ventana/Logo.png")).getImage());
        this.controladorPaciente = cp;
        cargarTabla();
        setLocationRelativeTo(null);
        
    }
    private void cargarTabla() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new String[]{"N° HC", "Apellidos y Nombres", "Tipo Doc", "N° Documento", "Sexo", "Edad", "Teléfono"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int col) { return false; }
    };

    int totalConsultas = 0;
    for (Modelo.Paciente p : controladorPaciente.getListaPacientes()) {
        modelo.addRow(new Object[]{
            p.getNumHC(),
            p.getNombreCompleto(),
            p.getTipodoc(),
            p.getNumdoc(),
            p.getSexo(),
            p.getEdad(),
            p.getTelefono()
        });
        totalConsultas += p.getConsultas().size();
    }

    jTable1.setModel(modelo);
    lblTotalPacientes.setText("Total pacientes: " + controladorPaciente.getListaPacientes().size());
    lblTotalConsultas.setText("Total consultas: " + totalConsultas);
    lblConsultasPaciente.setText("Consultas del paciente: -");

    // Click en fila para ver consultas del paciente seleccionado
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = jTable1.getSelectedRow();
            if (fila >= 0) {
                Modelo.Paciente p = controladorPaciente.getListaPacientes().get(fila);
                lblConsultasPaciente.setText("Consultas de " + p.getNombreCompleto() + ": " + p.getConsultas().size());
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        lblTotalPacientes = new javax.swing.JLabel();
        lblTotalConsultas = new javax.swing.JLabel();
        lblConsultasPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPListado.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Pacientes"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° HC", "Apellidos y Nombres", "Tipo Doc", "N° Doc", "Sexo", "Edad", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout JPListadoLayout = new javax.swing.GroupLayout(JPListado);
        JPListado.setLayout(JPListadoLayout);
        JPListadoLayout.setHorizontalGroup(
            JPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        JPListadoLayout.setVerticalGroup(
            JPListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        lblTotalPacientes.setText("jLabel1");

        lblTotalConsultas.setText("jLabel2");

        lblConsultasPaciente.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnCerrar)
                .addGap(101, 101, 101)
                .addComponent(lblTotalPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConsultasPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(lblTotalPacientes)
                    .addComponent(lblTotalConsultas)
                    .addComponent(lblConsultasPaciente))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPListado;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblConsultasPaciente;
    private javax.swing.JLabel lblTotalConsultas;
    private javax.swing.JLabel lblTotalPacientes;
    // End of variables declaration//GEN-END:variables
}
