/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import Controlador.ControladorPaciente;
import Modelo.FIsioterapeuta;
import Modelo.Recepcionista;
import Modelo.Usuario;

/**
 *
 * @author ACER
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    private ControladorPaciente controladorPaciente;
    private Usuario usuarioActual;//Upcasting: Se guarda como Usuario
    
    public FrmPrincipal(ControladorPaciente controladorPaciente1, Usuario usuario) {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Ventana/Logo.png")).getImage());
        this.usuarioActual = usuario;
        this.controladorPaciente = controladorPaciente1;
        configurarPermisos();
    }
    private void configurarPermisos() {
        //DOwncasting
    if (usuarioActual instanceof FIsioterapeuta) {
        btnRegistrarPaciente.setEnabled(true);
        btnRegistrarConsulta.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnCerrar.setEnabled(true);
        btnListado.setEnabled(true);
        lblBienvenida.setText(" Bienvenido Administrador --> Rol: Fisioterapeuta");
    }
    else if(usuarioActual instanceof Recepcionista)
    {
        btnRegistrarPaciente.setEnabled(true);
        btnRegistrarConsulta.setEnabled(false);
        btnBuscar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCerrar.setEnabled(true);
        btnListado.setEnabled(true);
        lblBienvenida.setText(" Bienvenido Recepcionista --> Rol: Recepcionista");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        btnRegistrarPaciente = new javax.swing.JButton();
        btnRegistrarConsulta = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnListado = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baganet - Menú Principal");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventana/Logo.png"))); // NOI18N
        lblLogo.setText("jLabel1");

        lblTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTitulo.setText("BAGANET MEDICINA REGENERATIVA - Sistema de Historias Clínicas");

        btnRegistrarPaciente.setText("Registrar Paciente");
        btnRegistrarPaciente.addActionListener(this::btnRegistrarPacienteActionPerformed);

        btnRegistrarConsulta.setText("Registrar Consulta");
        btnRegistrarConsulta.addActionListener(this::btnRegistrarConsultaActionPerformed);

        btnBuscar.setText("Buscar Historia Clínica");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnListado.setText("Listado de Pacientes");
        btnListado.addActionListener(this::btnListadoActionPerformed);

        btnActualizar.setText("Actualizar Datos");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar Paciente");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListado)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar))
                    .addComponent(lblTitulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrarPaciente)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(lblBienvenida)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarPaciente)
                            .addComponent(btnRegistrarConsulta)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnCerrar)
                            .addComponent(btnListado)
                            .addComponent(btnActualizar)))
                    .addComponent(lblLogo))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteActionPerformed
    FrmRegistroPa frm = new FrmRegistroPa(controladorPaciente);
    frm.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPacienteActionPerformed

    private void btnRegistrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarConsultaActionPerformed
    FrmRegistroCon frm = new FrmRegistroCon(controladorPaciente);
    frm.setVisible(true);
    }//GEN-LAST:event_btnRegistrarConsultaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    FrmBusquedaPaciente frm = new FrmBusquedaPaciente(controladorPaciente);
    frm.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
    FrmListadoPacientes frm = new FrmListadoPacientes(controladorPaciente);
    frm.setVisible(true);
    }//GEN-LAST:event_btnListadoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    FrmActualizarPaciente frm = new FrmActualizarPaciente(controladorPaciente);
    frm.setVisible(true);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    FrmEliminarPaciente frm = new FrmEliminarPaciente(controladorPaciente);
    frm.setVisible(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Desea cerrar sesión?",
        "Confirmar",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListado;
    private javax.swing.JButton btnRegistrarConsulta;
    private javax.swing.JButton btnRegistrarPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
