/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Controlador.ControladorPaciente;
import Modelo.AntecedentesMedicos;
import Modelo.Paciente;

/**
 *
 * @author ACER
 */
public class FrmRegistroPa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegistroPa.class.getName());

    /**
     * Creates new form FrmRegistroPa
     */
    private ControladorPaciente controladorPaciente;
    public FrmRegistroPa(ControladorPaciente controladorPaciente ) {
        initComponents();
        this.controladorPaciente = controladorPaciente;
        setLocationRelativeTo(null);
        lblMensaje.setText("");
        txtHC.setText("(automático)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosGenerales = new javax.swing.JPanel();
        lblHC = new javax.swing.JLabel();
        txtHC = new javax.swing.JTextField();
        lblTipoDoc = new javax.swing.JLabel();
        cmbTipoDoc = new javax.swing.JComboBox<>();
        lblNumDoc = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblPaterno = new javax.swing.JLabel();
        txtPaterno = new javax.swing.JTextField();
        lblMaterno = new javax.swing.JLabel();
        txtMaterno = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        rbF = new javax.swing.JRadioButton();
        rbM = new javax.swing.JRadioButton();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblFechaNac = new javax.swing.JLabel();
        txtFechaNac = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        pnlAntecedentes = new javax.swing.JPanel();
        lblApp = new javax.swing.JLabel();
        rbAppSi = new javax.swing.JRadioButton();
        rbAppNo = new javax.swing.JRadioButton();
        lblCirugia = new javax.swing.JLabel();
        rbCirugiaSi = new javax.swing.JRadioButton();
        rbCirugiasNo = new javax.swing.JRadioButton();
        lblIntoxi = new javax.swing.JLabel();
        rbIntoxiSi = new javax.swing.JRadioButton();
        rbIntoxiNo = new javax.swing.JRadioButton();
        lblTrabajo = new javax.swing.JLabel();
        rbTrabajoSi = new javax.swing.JRadioButton();
        rbTrabajoNo = new javax.swing.JRadioButton();
        lblDeporte = new javax.swing.JLabel();
        rbDeporteSi = new javax.swing.JRadioButton();
        rbDeporteNo = new javax.swing.JRadioButton();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblTalla = new javax.swing.JLabel();
        txtTalla = new javax.swing.JTextField();
        lblIMC = new javax.swing.JLabel();
        txtIMC = new javax.swing.JTextField();
        lblPA = new javax.swing.JLabel();
        txtPA = new javax.swing.JTextField();
        btnCalcularIMC = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDatosGenerales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        lblHC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHC.setText("HC:");

        txtHC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtHC.setEnabled(false);

        lblTipoDoc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTipoDoc.setText("Tipo de Documento:");

        cmbTipoDoc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".....", "DNI", "CE" }));

        lblNumDoc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNumDoc.setText("Número de Documento:");

        txtNumDoc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblNombres.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombres.setText("Nombres:");

        txtNombres.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblPaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPaterno.setText("Paterno:");

        txtPaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblMaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMaterno.setText("Materno:");

        txtMaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblSexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSexo.setText("Sexo:");

        rbF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbF.setText("F");

        rbM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbM.setText("M");

        lblEdad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEdad.setText("Edad:");

        txtEdad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblFechaNac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFechaNac.setText("Fecha de Nacimiento:");

        txtFechaNac.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDireccion.setText("Dirección:");

        txtDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTelefono.setText("Teléfono:");

        txtTelefono.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlDatosGeneralesLayout = new javax.swing.GroupLayout(pnlDatosGenerales);
        pnlDatosGenerales.setLayout(pnlDatosGeneralesLayout);
        pnlDatosGeneralesLayout.setHorizontalGroup(
            pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                            .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                                    .addComponent(lblHC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblNumDoc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                            .addComponent(lblNombres)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombres)))
                    .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                        .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                                .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rbF)
                                .addGap(18, 18, 18)
                                .addComponent(rbM)
                                .addGap(30, 30, 30)
                                .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                        .addComponent(lblFechaNac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                        .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDatosGeneralesLayout.setVerticalGroup(
            pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHC)
                    .addComponent(txtHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDoc)
                    .addComponent(cmbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumDoc)
                    .addComponent(txtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaterno)
                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(rbF)
                    .addComponent(rbM)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNac)
                    .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlAntecedentes.setBorder(javax.swing.BorderFactory.createTitledBorder("Antecedentes"));

        lblApp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblApp.setText("APP:");

        rbAppSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbAppSi.setText("Si");

        rbAppNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbAppNo.setText("No");

        lblCirugia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCirugia.setText("Cirugías:");

        rbCirugiaSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbCirugiaSi.setText("Si");

        rbCirugiasNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbCirugiasNo.setText("No");

        lblIntoxi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIntoxi.setText("Intoxicación:");

        rbIntoxiSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbIntoxiSi.setText("Si");

        rbIntoxiNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbIntoxiNo.setText("No");

        lblTrabajo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTrabajo.setText("Trabajo:");

        rbTrabajoSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbTrabajoSi.setText("Si");

        rbTrabajoNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbTrabajoNo.setText("No");

        lblDeporte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDeporte.setText("Deporte:");

        rbDeporteSi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbDeporteSi.setText("Si");

        rbDeporteNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbDeporteNo.setText("No");

        lblPeso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPeso.setText("Peso:");

        txtPeso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblTalla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTalla.setText("Talla:");

        txtTalla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblIMC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIMC.setText("IMC:");

        txtIMC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIMC.setEnabled(false);

        lblPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPA.setText("PA:");

        txtPA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnCalcularIMC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCalcularIMC.setText("Calcular IMC");
        btnCalcularIMC.addActionListener(this::btnCalcularIMCActionPerformed);

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblMensaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlAntecedentesLayout = new javax.swing.GroupLayout(pnlAntecedentes);
        pnlAntecedentes.setLayout(pnlAntecedentesLayout);
        pnlAntecedentesLayout.setHorizontalGroup(
            pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                        .addComponent(lblCirugia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCirugiaSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbCirugiasNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                        .addComponent(lblApp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbAppSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbAppNo)
                        .addGap(278, 278, 278)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                        .addComponent(lblIntoxi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbIntoxiSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbIntoxiNo))
                    .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                        .addComponent(lblTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTrabajoSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTrabajoNo)
                        .addGap(18, 18, 18)
                        .addComponent(lblDeporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDeporteSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDeporteNo))
                    .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                        .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                                .addComponent(lblPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                                .addComponent(lblPA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                                .addComponent(lblTalla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblIMC))
                            .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnCalcularIMC)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pnlAntecedentesLayout.setVerticalGroup(
            pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApp)
                            .addComponent(rbAppSi)
                            .addComponent(rbAppNo)))
                    .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnLimpiar)
                        .addComponent(btnCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCirugia)
                    .addComponent(rbCirugiaSi)
                    .addComponent(rbCirugiasNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntoxi)
                    .addComponent(rbIntoxiSi)
                    .addComponent(rbIntoxiNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrabajo)
                    .addComponent(rbTrabajoSi)
                    .addComponent(rbTrabajoNo)
                    .addComponent(lblDeporte)
                    .addComponent(rbDeporteSi)
                    .addComponent(rbDeporteNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTalla)
                    .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIMC)
                    .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAntecedentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPA)
                            .addComponent(btnCalcularIMC)))
                    .addGroup(pnlAntecedentesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblMensaje)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatosGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAntecedentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAntecedentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIMCActionPerformed
        try {
        double peso = Double.parseDouble(txtPeso.getText().trim());
        double talla = Double.parseDouble(txtTalla.getText().trim());

        if (peso <= 0 || talla <= 0) {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText("Peso y talla deben ser mayores a 0.");
            return;
        }

        double tallaMetros = talla / 100.0;
        double imc = peso / (tallaMetros * tallaMetros);

        txtIMC.setText(String.format("%.2f", imc));
        lblMensaje.setForeground(new java.awt.Color(0, 128, 0));
        lblMensaje.setText("IMC calculado correctamente.");

    } catch (NumberFormatException e) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("Ingrese valores numéricos válidos en Peso y Talla.");
    }
    }//GEN-LAST:event_btnCalcularIMCActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try 
        {
            String dni = txtNumDoc.getText().trim();

            // REQ-04
            if (controladorPaciente.existeDNI(dni)) 
            {
                lblMensaje.setForeground(java.awt.Color.RED);
                lblMensaje.setText("Ya existe un paciente registrado con ese DNI.");
                return;
            }

            // REQ-05
            String sexo;
            if (rbF.isSelected()) 
            {
                sexo = "F";
            } else if (rbM.isSelected()) 
            {
                sexo = "M";
            } else 
            {
                lblMensaje.setForeground(java.awt.Color.RED);
                lblMensaje.setText("Seleccione un sexo válido: F o M.");
                return;
            }

            // REQ-09
            AntecedentesMedicos antecedentes = new AntecedentesMedicos(
            rbAppSi.isSelected(),
            rbCirugiaSi.isSelected(),
            rbIntoxiSi.isSelected(),
            Double.parseDouble(txtPeso.getText().trim()),
            Double.parseDouble(txtTalla.getText().trim()),
            txtPA.getText().trim(),
            rbTrabajoSi.isSelected(),
            rbDeporteSi.isSelected()
            );

            // REQ-01,02,03,05,06,07,08
            Paciente nuevoPaciente = new Paciente(
            0,
            (String) cmbTipoDoc.getSelectedItem(),
            dni,
            txtPaterno.getText().trim(),
            txtMaterno.getText().trim(),
            txtNombres.getText().trim(),
            sexo,
            Integer.parseInt(txtEdad.getText().trim()),
            txtFechaNac.getText().trim(),
            txtDireccion.getText().trim(),
            txtTelefono.getText().trim(),
            antecedentes
            );

            // REQ-11
            int hc = controladorPaciente.registrarPaciente(nuevoPaciente);

            txtHC.setText(String.valueOf(hc));
            txtIMC.setText(String.format("%.2f", antecedentes.getImc()));

            lblMensaje.setForeground(new java.awt.Color(0, 128, 0));
            lblMensaje.setText("Paciente registrado correctamente. N° HC: " + hc);

            } catch (NumberFormatException e) 
            {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText("Ingrese una edad válida.");
            } catch (IllegalArgumentException e) 
            {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText(e.getMessage());
            }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtHC.setText("(automático)");
        cmbTipoDoc.setSelectedIndex(0);
        txtNumDoc.setText("");
        txtNombres.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");

        rbF.setSelected(false);
        rbM.setSelected(false);

        txtEdad.setText("");
        txtFechaNac.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");

        rbAppSi.setSelected(false);
        rbAppNo.setSelected(false);
        rbCirugiaSi.setSelected(false);
        rbCirugiasNo.setSelected(false);
        rbIntoxiSi.setSelected(false);
        rbIntoxiNo.setSelected(false);
        rbTrabajoSi.setSelected(false);
        rbTrabajoNo.setSelected(false);
        rbDeporteSi.setSelected(false);
        rbDeporteNo.setSelected(false);

        txtPeso.setText("");
        txtTalla.setText("");
        txtIMC.setText("");
        txtPA.setText("");

        lblMensaje.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularIMC;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbTipoDoc;
    private javax.swing.JLabel lblApp;
    private javax.swing.JLabel lblCirugia;
    private javax.swing.JLabel lblDeporte;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblHC;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblIntoxi;
    private javax.swing.JLabel lblMaterno;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNumDoc;
    private javax.swing.JLabel lblPA;
    private javax.swing.JLabel lblPaterno;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JLabel lblTrabajo;
    private javax.swing.JPanel pnlAntecedentes;
    private javax.swing.JPanel pnlDatosGenerales;
    private javax.swing.JRadioButton rbAppNo;
    private javax.swing.JRadioButton rbAppSi;
    private javax.swing.JRadioButton rbCirugiaSi;
    private javax.swing.JRadioButton rbCirugiasNo;
    private javax.swing.JRadioButton rbDeporteNo;
    private javax.swing.JRadioButton rbDeporteSi;
    private javax.swing.JRadioButton rbF;
    private javax.swing.JRadioButton rbIntoxiNo;
    private javax.swing.JRadioButton rbIntoxiSi;
    private javax.swing.JRadioButton rbM;
    private javax.swing.JRadioButton rbTrabajoNo;
    private javax.swing.JRadioButton rbTrabajoSi;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtHC;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
