/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import Controlador.ControladorPaciente;
import Modelo.Paciente;
import Modelo.Consulta;

/**
 *
 * @author ACER
 */
public class FrmRegistroCon extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegistroCon.class.getName());
    private ControladorPaciente controladorPaciente;
    private Paciente pacienteEncontrado;
    /**
     * Creates new form FrmRegistroCon
     */
    public FrmRegistroCon(ControladorPaciente controladorPaciente) {
        initComponents();
        this.controladorPaciente = controladorPaciente;
        setLocationRelativeTo(null);
        lblMensaje.setText("");
        habilitarFormularioConsulta(false);
    }
    private void limpiarFormularioConsulta() {
    txtFecha.setText("");
    txtarMotivo.setText("");
    txtPeso.setText("");
    txtTalla.setText("");
    txtIMC.setText("");
    txtPA.setText("");
    txtO3.setText("");
    txtPRP.setText("");
    txtTerapia.setText("");
    txtAreaIndicaciones.setText("");
    txtAreaDiagnos.setText("");
}
    
    private void habilitarFormularioConsulta(boolean estado) {
    txtFecha.setEnabled(estado);
    txtarMotivo.setEnabled(estado);
    txtPeso.setEnabled(estado);
    txtTalla.setEnabled(estado);
    txtPA.setEnabled(estado);
    txtO3.setEnabled(estado);
    txtPRP.setEnabled(estado);
    txtTerapia.setEnabled(estado);
    txtAreaIndicaciones.setEnabled(estado);
    txtAreaDiagnos.setEnabled(estado);
    btnCalcularIMC.setEnabled(estado);
    btnGuardar.setEnabled(estado);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBuscarPaciente = new javax.swing.JPanel();
        lblBuscarDNi = new javax.swing.JLabel();
        txtBuscarDNI = new javax.swing.JTextField();
        btnBuscarDNI = new javax.swing.JButton();
        lblNombrePaciente = new javax.swing.JLabel();
        jpDatosConsulta = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblMotivo = new javax.swing.JLabel();
        jscrollMotivo = new javax.swing.JScrollPane();
        txtarMotivo = new javax.swing.JTextArea();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblTalla = new javax.swing.JLabel();
        txtTalla = new javax.swing.JTextField();
        lblIMC = new javax.swing.JLabel();
        txtIMC = new javax.swing.JTextField();
        lblPA = new javax.swing.JLabel();
        txtPA = new javax.swing.JTextField();
        btnCalcularIMC = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblO3 = new javax.swing.JLabel();
        lblPRP = new javax.swing.JLabel();
        txtO3 = new javax.swing.JTextField();
        txtPRP = new javax.swing.JTextField();
        lblTerapia = new javax.swing.JLabel();
        txtTerapia = new javax.swing.JTextField();
        lblIndicaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaIndicaciones = new javax.swing.JTextArea();
        lblDiagnostico = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDiagnos = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBuscarPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Paciente"));

        lblBuscarDNi.setText("N° de Documento del Paciente");

        btnBuscarDNI.setText("Buscar");
        btnBuscarDNI.addActionListener(this::btnBuscarDNIActionPerformed);

        lblNombrePaciente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpBuscarPacienteLayout = new javax.swing.GroupLayout(jpBuscarPaciente);
        jpBuscarPaciente.setLayout(jpBuscarPacienteLayout);
        jpBuscarPacienteLayout.setHorizontalGroup(
            jpBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBuscarPacienteLayout.createSequentialGroup()
                        .addComponent(lblBuscarDNi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnBuscarDNI)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBuscarPacienteLayout.setVerticalGroup(
            jpBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarDNi)
                    .addComponent(txtBuscarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDNI))
                .addGap(18, 18, 18)
                .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpDatosConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder("Motivo / Examen Físico"));

        lblFecha.setText("Fecha:");

        lblMotivo.setText("Motivo:");

        txtarMotivo.setColumns(20);
        txtarMotivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtarMotivo.setRows(5);
        jscrollMotivo.setViewportView(txtarMotivo);

        lblPeso.setText("Peso:");

        lblTalla.setText("Talla:");

        lblIMC.setText("IMC:");

        txtIMC.setEnabled(false);

        lblPA.setText("PA:");

        btnCalcularIMC.setText("Calcular IMC");
        btnCalcularIMC.addActionListener(this::btnCalcularIMCActionPerformed);

        javax.swing.GroupLayout jpDatosConsultaLayout = new javax.swing.GroupLayout(jpDatosConsulta);
        jpDatosConsulta.setLayout(jpDatosConsultaLayout);
        jpDatosConsultaLayout.setHorizontalGroup(
            jpDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosConsultaLayout.createSequentialGroup()
                        .addComponent(lblMotivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jscrollMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDatosConsultaLayout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDatosConsultaLayout.createSequentialGroup()
                        .addComponent(lblPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTalla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIMC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btnCalcularIMC)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpDatosConsultaLayout.setVerticalGroup(
            jpDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscrollMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDatosConsultaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblMotivo)))
                .addGap(20, 20, 20)
                .addGroup(jpDatosConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTalla)
                    .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIMC)
                    .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPA)
                    .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularIMC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Indicaciones / Tratamiento"));

        lblO3.setText("O3:");

        lblPRP.setText("PRP:");

        lblTerapia.setText("Terapia:");

        lblIndicaciones.setText("Indicaciones:");

        txtAreaIndicaciones.setColumns(20);
        txtAreaIndicaciones.setRows(5);
        jScrollPane1.setViewportView(txtAreaIndicaciones);

        lblDiagnostico.setText("Diagnóstico:");

        txtAreaDiagnos.setColumns(20);
        txtAreaDiagnos.setRows(5);
        jScrollPane2.setViewportView(txtAreaDiagnos);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblMensaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPRP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPRP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblO3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtO3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTerapia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTerapia, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDiagnostico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIndicaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardar)
                                    .addComponent(btnLimpiar)
                                    .addComponent(btnCancelar))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblO3)
                            .addComponent(txtO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPRP)
                    .addComponent(txtPRP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerapia)
                    .addComponent(txtTerapia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblIndicaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDiagnostico)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBuscarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpDatosConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDatosConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    if (pacienteEncontrado == null) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("Primero busque un paciente válido.");
        return;
    }

    try {
        double peso = Double.parseDouble(txtPeso.getText().trim());
        double talla = Double.parseDouble(txtTalla.getText().trim());

        Consulta nuevaConsulta = new Consulta(
            txtFecha.getText().trim(),
            txtarMotivo.getText().trim(),
            peso,
            talla,
            txtPA.getText().trim(),
            txtO3.getText().trim(),
            txtPRP.getText().trim(),
            txtTerapia.getText().trim(),
            txtAreaIndicaciones.getText().trim(),
            txtAreaDiagnos.getText().trim()
        );

        pacienteEncontrado.agregarConsulta(nuevaConsulta);

        txtIMC.setText(String.format("%.2f", nuevaConsulta.getImc()));

        lblMensaje.setForeground(new java.awt.Color(0, 128, 0));
        lblMensaje.setText("Consulta registrada correctamente.");

        limpiarFormularioConsulta();

    } catch (NumberFormatException e) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("Ingrese valores numéricos válidos en Peso y Talla.");
    } catch (IllegalArgumentException e) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText(e.getMessage());
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormularioConsulta();
        lblMensaje.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIMCActionPerformed
    try {
        double peso = Double.parseDouble(txtPeso.getText().trim());
        double talla = Double.parseDouble(txtTalla.getText().trim());

        if (peso <= 0 || talla <= 0) {
            lblMensaje.setForeground(java.awt.Color.RED);
            lblMensaje.setText("Peso y talla deben ser mayores a 0.");
            return;
        }

        double tallaMetros = talla / 100.0;
        double imc = peso / (tallaMetros * tallaMetros);

        txtIMC.setText(String.format("%.2f", imc));
        lblMensaje.setForeground(new java.awt.Color(0, 128, 0));
        lblMensaje.setText("IMC calculado correctamente.");

    } catch (NumberFormatException e) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("Ingrese valores numéricos válidos en Peso y Talla.");
    }
    }//GEN-LAST:event_btnCalcularIMCActionPerformed

    private void btnBuscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDNIActionPerformed
        String dni = txtBuscarDNI.getText().trim();

    if (dni.isEmpty()) {
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("Ingrese un DNI para buscar.");
        return;
    }

    pacienteEncontrado = controladorPaciente.buscarPorDNI(dni);

    if (pacienteEncontrado != null) {
        lblNombrePaciente.setText("Paciente: " + pacienteEncontrado.getNombreCompleto()
                + "  |  N° HC: " + pacienteEncontrado.getNumHC());
        lblMensaje.setForeground(new java.awt.Color(0, 128, 0));
        lblMensaje.setText("Paciente encontrado. Complete los datos de la consulta.");
        habilitarFormularioConsulta(true);
    } else {
        lblNombrePaciente.setText("");
        lblMensaje.setForeground(java.awt.Color.RED);
        lblMensaje.setText("No se encontró ningún paciente con ese DNI.");
        habilitarFormularioConsulta(false);
        pacienteEncontrado = null;
    }
    }//GEN-LAST:event_btnBuscarDNIActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDNI;
    private javax.swing.JButton btnCalcularIMC;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpBuscarPaciente;
    private javax.swing.JPanel jpDatosConsulta;
    private javax.swing.JScrollPane jscrollMotivo;
    private javax.swing.JLabel lblBuscarDNi;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIMC;
    private javax.swing.JLabel lblIndicaciones;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JLabel lblO3;
    private javax.swing.JLabel lblPA;
    private javax.swing.JLabel lblPRP;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JLabel lblTerapia;
    private javax.swing.JTextArea txtAreaDiagnos;
    private javax.swing.JTextArea txtAreaIndicaciones;
    private javax.swing.JTextField txtBuscarDNI;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtO3;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPRP;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTerapia;
    private javax.swing.JTextArea txtarMotivo;
    // End of variables declaration//GEN-END:variables
}
